# DB Setup
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/get_locals_auth?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 8574
  jpa:
    hibernate:
      ddl-auto: update

# Logging
logging:
  level:
    org.springframework:
      security: INFO
      web: DEBUG
      boot: INFO
    org.hibernate: ERROR
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
# Server Setup
server:
  address: 10.0.0.253
  port: 8080