# DB Setup
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/get_locals_auth?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 8574
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB

# Logging
logging:
  level:
    org.springframework:
      web: DEBUG
    org.hibernate: ERROR
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

  file:
      name: logs/app.log
# Server Setup
server:
  address: 10.0.0.253
  port: 8080